# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "flati"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["daveed, housekeeping"]
  s.date = "2013-06-13"
  s.description = "flati wraps and installs the bootstrap theme Flati into a rails asset pipeline."
  s.email = "david.alphen@gmail.com, carl@house-keeping.com"
  s.extra_rdoc_files = [
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/fonts/flati/ecoico.eot",
    "app/assets/fonts/flati/ecoico.svg",
    "app/assets/fonts/flati/ecoico.ttf",
    "app/assets/fonts/flati/ecoico.woff",
    "app/assets/fonts/flati/fontawesome-webfont.eot",
    "app/assets/fonts/flati/fontawesome-webfont.svg",
    "app/assets/fonts/flati/fontawesome-webfont.ttf",
    "app/assets/fonts/flati/fontawesome-webfont.woff",
    "app/assets/fonts/flati/zocial-regular-webfont.eot",
    "app/assets/fonts/flati/zocial-regular-webfont.svg",
    "app/assets/fonts/flati/zocial-regular-webfont.ttf",
    "app/assets/fonts/flati/zocial-regular-webfont.woff",
    "app/assets/images/flati/accordion.png",
    "app/assets/images/flati/client1.png",
    "app/assets/images/flati/client2.png",
    "app/assets/images/flati/client3.png",
    "app/assets/images/flati/client4.png",
    "app/assets/images/flati/client5.png",
    "app/assets/images/flati/client6.png",
    "app/assets/images/flati/dummy.png",
    "app/assets/images/flati/lines.png",
    "app/assets/images/flati/main_carousel_nav.png",
    "app/assets/images/flati/next-light.png",
    "app/assets/images/flati/play-pause-light.png",
    "app/assets/images/flati/preload_img.gif",
    "app/assets/images/flati/prev-light.png",
    "app/assets/images/flati/ribbon.png",
    "app/assets/images/flati/slider_nav.png",
    "app/assets/images/flati/zoom.png",
    "app/assets/javascripts/flati/bootstrap.min.js",
    "app/assets/javascripts/flati/flati.js.coffee",
    "app/assets/javascripts/flati/jPages.js",
    "app/assets/javascripts/flati/jquery-ui.min.js",
    "app/assets/javascripts/flati/jquery.carouFredSel-6.2.1-packed.js",
    "app/assets/javascripts/flati/jquery.catslider.js",
    "app/assets/javascripts/flati/jquery.isotope.min.js",
    "app/assets/javascripts/flati/jquery.js",
    "app/assets/javascripts/flati/jquery.mousewheel.min.js",
    "app/assets/javascripts/flati/jquery.nerveSlider.min.js",
    "app/assets/javascripts/flati/jquery.nivo.slider.pack.js",
    "app/assets/javascripts/flati/jquery.prettyPhoto.js",
    "app/assets/javascripts/flati/jquery.socialist.min.js",
    "app/assets/javascripts/flati/jquery.touchSwipe.min.js",
    "app/assets/javascripts/flati/modernizr.custom.63321.js",
    "app/assets/javascripts/flati/modernizr.custom.js",
    "app/assets/javascripts/flati/scripts.js",
    "app/assets/javascripts/flati/superfish.js",
    "app/assets/stylesheets/flati.sass",
    "app/assets/stylesheets/flati/accordian.sass",
    "app/assets/stylesheets/flati/alt_footer.sass",
    "app/assets/stylesheets/flati/bootstrap.sass",
    "app/assets/stylesheets/flati/flati.sass",
    "app/assets/stylesheets/flati/font-awesome-ie7.sass",
    "app/assets/stylesheets/flati/font-awesome.sass",
    "app/assets/stylesheets/flati/fonts.sass",
    "app/assets/stylesheets/flati/mainsite.css.sass",
    "app/assets/stylesheets/flati/nerveslider.sass",
    "app/assets/stylesheets/flati/prettify.sass",
    "app/assets/stylesheets/flati/prettyPhoto.css",
    "app/assets/stylesheets/flati/pricing.css",
    "app/assets/stylesheets/flati/slider.sass",
    "app/assets/stylesheets/flati/socialist.sass",
    "app/assets/stylesheets/flati/style.css",
    "app/assets/stylesheets/flati/theme.sass",
    "app/assets/stylesheets/flati/timeline.sass",
    "app/assets/stylesheets/flati/zocial.sass",
    "flati.gemspec",
    "lib/flati.rb",
    "lib/flati/engine.rb"
  ]
  s.homepage = "http://github.com/daveed/flati"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "flati wraps and installs the bootstrap theme Flati into a rails asset pipeline."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

