# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "flati"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["daveed, housekeeping"]
  s.date = "2013-06-13"
  s.description = "flati wraps and installs the bootstrap theme Flati into a rails asset pipeline."
  s.email = "david.alphen@gmail.com, carl@house-keeping.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "VERSION"
  ]
  s.homepage = "http://github.com/daveed/flati"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "flati wraps and installs the bootstrap theme Flati into a rails asset pipeline."

  s.add_dependency "sass-rails", "~> 3.2.5"
  s.add_dependency "coffee-rails", "~> 3.2.2"

end
